version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      prefix-development: build
      include: scope

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    commit-message:
      prefix: build
      include: scope
