services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      # Uncomment the following line to expose MongoDB outside of the Docker Compose network.
      # Make sure to secure your MongoDB instance if you do so!
      #- 27017:27017
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/keneanung/crowdmap-crowdsource-service:latest
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3000:3000
    # change this if you want to keep your version stable. This will pull a new service image on every start.
    #pull_policy: always
    environment:
      # The URL where to download the current map file as baseline from
      - MAP_DOWNLOAD_URL=https://ire-mudlet-mapping.github.io/AchaeaCrowdmap/Map/map
      # The URL where to download the version file of the baseline map from.
      - VERSION_DOWNLOAD_URL=https://ire-mudlet-mapping.github.io/AchaeaCrowdmap/Map/version.txt
      # The port the node service is listening on. If you change this value, be sure to modify the port mapping above as well.
      - PORT=3000
      # The file path where the map file is saved within the container. You should not need to set this.
      - MAP_FILE=/opt/serve/map
      # The file path where the version file is saved within the container. You should not need to set this.
      - VERSION_FILE=/opt/serve/version
      # Local MongoDB connection string. Adjust credentials / auth if you secure the mongo service.
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      # The MongoDB database to use.
      - MONGO_DB_NAME=crowdmap
      # Which reverse proxy to trust to return the real IP address of the client. Set to 0 to trust no proxy. See https://expressjs.com/en/guide/behind-proxies.html for further documentation.
      # This implementation uses the number option only.
      # Use the /utility/ip endpoint to check if the real IP is returned correctly.
      - TRUST_PROXY=0
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000/utility/healthcheck || exit 1"
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 5s

volumes:
  mongo-data: