services:
  app:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/keneanung/crowdmap-crowdsource-service:latest
    ports:
      - 3000:3000
    environment:
      - MAP_DOWNLOAD_URL=https://ire-mudlet-mapping.github.io/AchaeaCrowdmap/Map/map
      - VERSION_DOWNLOAD_URL=https://ire-mudlet-mapping.github.io/AchaeaCrowdmap/Map/version.txt
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - MONGO_DB_NAME=${MONGO_DB_NAME}