name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3.0.0
    - uses: docker/build-push-action@v5.1.0
      with:
        push: ${{GITHUB_EVENT_NAME == "push" }}
        tags: crowdmap-crowdsource-service:latest,crowdmap-crowdsource-service:$(date +%s)
        target: prod
        
